[project]
name = "CatSender"
version = "0.1.0"
description = "Simple send cats into telegram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiodns>=3.5.0",
    "aiogram>=3.22.0",
    "aiohttp>=3.12.15",
    "loguru>=0.7.3",
    "pydantic-settings>=2.11.0",
]
