[project]
name = "CatSender"
version = "0.1.0"
description = "Simple send cats into telegram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "pydantic-settings>=2.11.0",
]
